# Generated by Django 5.0 on 2023-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo', models.FileField(upload_to='static/')),
            ],
        ),
    ]
