# Generated by Django 5.0 on 2023-12-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='demo',
            field=models.FileField(upload_to=''),
        ),
    ]
